### ISSUE TITLE
Feature request: elapsed and/or simulation start time

### ISSUE THREAD

**Issue by TmLev** [uazu/stakker#14]
It would be nice to have shorthand methods for getting elapsed time since the simulation start and/or getting the simulation start time directly (should be more flexible).

**Comment by uazu** [comment]
This got me thinking for the last couple of days. Internally the timers do use a relative time, i.e. elapsed time since runtime startup. However the only thing that is exposed is `Instant`. It might be more consistent to invent a new time type `MonoTime` which is internally like a Duration, and use that instead of `Instant` for most things. For simulations you could start it at zero, which means that the elapsed time is easily available. For realtime, we'd need `MonoTime` to be relative to some `Instant`. If I switched to `MonoTime` then that would simplify the timer code. Since I'm planning a rewrite of the timer queue at some point, it would make sense to do those changes together. This would be a breaking change, so it would be for 0.3. So that would be a cleaner longer-term change that makes all this time-handling easier. It would also be more efficient on platforms like MacOS that have awkward Instant implementations, i.e. where add/sub operations involve more complicated calculations.

However, in the meantime I can add a method to Core to get the Instant that the runtime started, so you could access it as `cx.start_time()`, or something similar to that.

**Comment by TmLev** [comment]
That would be great!

**Comment by uazu** [comment]
Okay, this has been implemented in version 0.2.4. See `Core::start_instant()`, i.e. `cx.start_instant()` or whatever.
